// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
impl super::Client {
    /// Constructs a fluent builder for the
    /// [`DeleteCustomizationPermissions`](crate::operation::delete_customization_permissions::builders::DeleteCustomizationPermissionsFluentBuilder)
    /// operation.
    ///
    /// - The fluent builder is configurable:
    ///   - [`identifier(impl Into<String>)`](crate::operation::delete_customization_permissions::builders::DeleteCustomizationPermissionsFluentBuilder::identifier) / [`set_identifier(Option<String>)`](crate::operation::delete_customization_permissions::builders::DeleteCustomizationPermissionsFluentBuilder::set_identifier):<br>required: **true**<br>(undocumented)<br>
    /// - On success, responds with [`DeleteCustomizationPermissionsOutput`](crate::operation::delete_customization_permissions::DeleteCustomizationPermissionsOutput)
    /// - On failure, responds with [`SdkError<DeleteCustomizationPermissionsError>`](crate::operation::delete_customization_permissions::DeleteCustomizationPermissionsError)
    pub fn delete_customization_permissions(
        &self,
    ) -> crate::operation::delete_customization_permissions::builders::DeleteCustomizationPermissionsFluentBuilder {
        crate::operation::delete_customization_permissions::builders::DeleteCustomizationPermissionsFluentBuilder::new(
            self.handle.clone(),
        )
    }
}
