// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub fn ser_create_profile_input_input(
    object: &mut ::aws_smithy_json::serialize::JsonObjectWriter,
    input: &crate::operation::create_profile::CreateProfileInput,
) -> ::std::result::Result<(), ::aws_smithy_types::error::operation::SerializationError> {
    if let Some(var_1) = &input.identity_source {
        #[allow(unused_mut)]
        let mut object_2 = object.key("identitySource").start_object();
        crate::protocol_serde::shape_identity_source::ser_identity_source(&mut object_2, var_1)?;
        object_2.finish();
    }
    if let Some(var_3) = &input.profile_name {
        object.key("profileName").string(var_3.as_str());
    }
    if let Some(var_4) = &input.description {
        object.key("description").string(var_4.as_str());
    }
    if let Some(var_5) = &input.reference_tracker_configuration {
        #[allow(unused_mut)]
        let mut object_6 = object.key("referenceTrackerConfiguration").start_object();
        crate::protocol_serde::shape_reference_tracker_configuration::ser_reference_tracker_configuration(
            &mut object_6,
            var_5,
        )?;
        object_6.finish();
    }
    if let Some(var_7) = &input.active_functionalities {
        let mut array_8 = object.key("activeFunctionalities").start_array();
        for item_9 in var_7 {
            {
                array_8.value().string(item_9.as_str());
            }
        }
        array_8.finish();
    }
    if let Some(var_10) = &input.client_token {
        object.key("clientToken").string(var_10.as_str());
    }
    if let Some(var_11) = &input.kms_key_arn {
        object.key("kmsKeyArn").string(var_11.as_str());
    }
    if let Some(var_12) = &input.tags {
        let mut array_13 = object.key("tags").start_array();
        for item_14 in var_12 {
            {
                #[allow(unused_mut)]
                let mut object_15 = array_13.value().start_object();
                crate::protocol_serde::shape_tag::ser_tag(&mut object_15, item_14)?;
                object_15.finish();
            }
        }
        array_13.finish();
    }
    if let Some(var_16) = &input.resource_policy {
        #[allow(unused_mut)]
        let mut object_17 = object.key("resourcePolicy").start_object();
        crate::protocol_serde::shape_resource_policy::ser_resource_policy(&mut object_17, var_16)?;
        object_17.finish();
    }
    if let Some(var_18) = &input.opt_in_features {
        #[allow(unused_mut)]
        let mut object_19 = object.key("optInFeatures").start_object();
        crate::protocol_serde::shape_opt_in_features::ser_opt_in_features(&mut object_19, var_18)?;
        object_19.finish();
    }
    Ok(())
}
