// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq)]
pub struct GetPluginOutput {
    #[allow(missing_docs)] // documentation missing in model
    pub plugin_provider: ::std::string::String,
    #[allow(missing_docs)] // documentation missing in model
    pub plugin_id: ::std::string::String,
    #[allow(missing_docs)] // documentation missing in model
    pub plugin_credential: ::std::option::Option<crate::types::PluginCredential>,
    #[allow(missing_docs)] // documentation missing in model
    pub plugin_properties:
        ::std::option::Option<::std::collections::HashMap<::std::string::String, ::std::string::String>>,
    #[allow(missing_docs)] // documentation missing in model
    pub creation_time: ::std::option::Option<::aws_smithy_types::DateTime>,
    _request_id: Option<String>,
}
impl GetPluginOutput {
    #[allow(missing_docs)] // documentation missing in model
    pub fn plugin_provider(&self) -> &str {
        use std::ops::Deref;
        self.plugin_provider.deref()
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn plugin_id(&self) -> &str {
        use std::ops::Deref;
        self.plugin_id.deref()
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn plugin_credential(&self) -> ::std::option::Option<&crate::types::PluginCredential> {
        self.plugin_credential.as_ref()
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn plugin_properties(
        &self,
    ) -> ::std::option::Option<&::std::collections::HashMap<::std::string::String, ::std::string::String>> {
        self.plugin_properties.as_ref()
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn creation_time(&self) -> ::std::option::Option<&::aws_smithy_types::DateTime> {
        self.creation_time.as_ref()
    }
}
impl ::std::fmt::Debug for GetPluginOutput {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        let mut formatter = f.debug_struct("GetPluginOutput");
        formatter.field("plugin_provider", &self.plugin_provider);
        formatter.field("plugin_id", &self.plugin_id);
        formatter.field("plugin_credential", &"*** Sensitive Data Redacted ***");
        formatter.field("plugin_properties", &self.plugin_properties);
        formatter.field("creation_time", &self.creation_time);
        formatter.field("_request_id", &self._request_id);
        formatter.finish()
    }
}
impl ::aws_types::request_id::RequestId for GetPluginOutput {
    fn request_id(&self) -> Option<&str> {
        self._request_id.as_deref()
    }
}
impl GetPluginOutput {
    /// Creates a new builder-style object to manufacture
    /// [`GetPluginOutput`](crate::operation::get_plugin::GetPluginOutput).
    pub fn builder() -> crate::operation::get_plugin::builders::GetPluginOutputBuilder {
        crate::operation::get_plugin::builders::GetPluginOutputBuilder::default()
    }
}

/// A builder for [`GetPluginOutput`](crate::operation::get_plugin::GetPluginOutput).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default)]
#[non_exhaustive]
pub struct GetPluginOutputBuilder {
    pub(crate) plugin_provider: ::std::option::Option<::std::string::String>,
    pub(crate) plugin_id: ::std::option::Option<::std::string::String>,
    pub(crate) plugin_credential: ::std::option::Option<crate::types::PluginCredential>,
    pub(crate) plugin_properties:
        ::std::option::Option<::std::collections::HashMap<::std::string::String, ::std::string::String>>,
    pub(crate) creation_time: ::std::option::Option<::aws_smithy_types::DateTime>,
    _request_id: Option<String>,
}
impl GetPluginOutputBuilder {
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn plugin_provider(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.plugin_provider = ::std::option::Option::Some(input.into());
        self
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn set_plugin_provider(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.plugin_provider = input;
        self
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn get_plugin_provider(&self) -> &::std::option::Option<::std::string::String> {
        &self.plugin_provider
    }

    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn plugin_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.plugin_id = ::std::option::Option::Some(input.into());
        self
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn set_plugin_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.plugin_id = input;
        self
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn get_plugin_id(&self) -> &::std::option::Option<::std::string::String> {
        &self.plugin_id
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn plugin_credential(mut self, input: crate::types::PluginCredential) -> Self {
        self.plugin_credential = ::std::option::Option::Some(input);
        self
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn set_plugin_credential(mut self, input: ::std::option::Option<crate::types::PluginCredential>) -> Self {
        self.plugin_credential = input;
        self
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn get_plugin_credential(&self) -> &::std::option::Option<crate::types::PluginCredential> {
        &self.plugin_credential
    }

    /// Adds a key-value pair to `plugin_properties`.
    ///
    /// To override the contents of this collection use
    /// [`set_plugin_properties`](Self::set_plugin_properties).
    pub fn plugin_properties(
        mut self,
        k: impl ::std::convert::Into<::std::string::String>,
        v: impl ::std::convert::Into<::std::string::String>,
    ) -> Self {
        let mut hash_map = self.plugin_properties.unwrap_or_default();
        hash_map.insert(k.into(), v.into());
        self.plugin_properties = ::std::option::Option::Some(hash_map);
        self
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn set_plugin_properties(
        mut self,
        input: ::std::option::Option<::std::collections::HashMap<::std::string::String, ::std::string::String>>,
    ) -> Self {
        self.plugin_properties = input;
        self
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn get_plugin_properties(
        &self,
    ) -> &::std::option::Option<::std::collections::HashMap<::std::string::String, ::std::string::String>> {
        &self.plugin_properties
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn creation_time(mut self, input: ::aws_smithy_types::DateTime) -> Self {
        self.creation_time = ::std::option::Option::Some(input);
        self
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn set_creation_time(mut self, input: ::std::option::Option<::aws_smithy_types::DateTime>) -> Self {
        self.creation_time = input;
        self
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn get_creation_time(&self) -> &::std::option::Option<::aws_smithy_types::DateTime> {
        &self.creation_time
    }

    pub(crate) fn _request_id(mut self, request_id: impl Into<String>) -> Self {
        self._request_id = Some(request_id.into());
        self
    }

    pub(crate) fn _set_request_id(&mut self, request_id: Option<String>) -> &mut Self {
        self._request_id = request_id;
        self
    }

    /// Consumes the builder and constructs a
    /// [`GetPluginOutput`](crate::operation::get_plugin::GetPluginOutput). This method will
    /// fail if any of the following fields are not set:
    /// - [`plugin_provider`](crate::operation::get_plugin::builders::GetPluginOutputBuilder::plugin_provider)
    /// - [`plugin_id`](crate::operation::get_plugin::builders::GetPluginOutputBuilder::plugin_id)
    pub fn build(
        self,
    ) -> ::std::result::Result<
        crate::operation::get_plugin::GetPluginOutput,
        ::aws_smithy_types::error::operation::BuildError,
    > {
        ::std::result::Result::Ok(crate::operation::get_plugin::GetPluginOutput {
            plugin_provider: self.plugin_provider.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "plugin_provider",
                    "plugin_provider was not specified but it is required when building GetPluginOutput",
                )
            })?,
            plugin_id: self.plugin_id.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "plugin_id",
                    "plugin_id was not specified but it is required when building GetPluginOutput",
                )
            })?,
            plugin_credential: self.plugin_credential,
            plugin_properties: self.plugin_properties,
            creation_time: self.creation_time,
            _request_id: self._request_id,
        })
    }
}
impl ::std::fmt::Debug for GetPluginOutputBuilder {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        let mut formatter = f.debug_struct("GetPluginOutputBuilder");
        formatter.field("plugin_provider", &self.plugin_provider);
        formatter.field("plugin_id", &self.plugin_id);
        formatter.field("plugin_credential", &"*** Sensitive Data Redacted ***");
        formatter.field("plugin_properties", &self.plugin_properties);
        formatter.field("creation_time", &self.creation_time);
        formatter.field("_request_id", &self._request_id);
        formatter.finish()
    }
}
