// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct CodeAnalysisUploadContext {
    /// Code analysis scan name
    pub code_scan_name: ::std::string::String,
}
impl CodeAnalysisUploadContext {
    /// Code analysis scan name
    pub fn code_scan_name(&self) -> &str {
        use std::ops::Deref;
        self.code_scan_name.deref()
    }
}
impl CodeAnalysisUploadContext {
    /// Creates a new builder-style object to manufacture
    /// [`CodeAnalysisUploadContext`](crate::types::CodeAnalysisUploadContext).
    pub fn builder() -> crate::types::builders::CodeAnalysisUploadContextBuilder {
        crate::types::builders::CodeAnalysisUploadContextBuilder::default()
    }
}

/// A builder for [`CodeAnalysisUploadContext`](crate::types::CodeAnalysisUploadContext).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct CodeAnalysisUploadContextBuilder {
    pub(crate) code_scan_name: ::std::option::Option<::std::string::String>,
}
impl CodeAnalysisUploadContextBuilder {
    /// Code analysis scan name
    /// This field is required.
    pub fn code_scan_name(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.code_scan_name = ::std::option::Option::Some(input.into());
        self
    }

    /// Code analysis scan name
    pub fn set_code_scan_name(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.code_scan_name = input;
        self
    }

    /// Code analysis scan name
    pub fn get_code_scan_name(&self) -> &::std::option::Option<::std::string::String> {
        &self.code_scan_name
    }

    /// Consumes the builder and constructs a
    /// [`CodeAnalysisUploadContext`](crate::types::CodeAnalysisUploadContext). This method will
    /// fail if any of the following fields are not set:
    /// - [`code_scan_name`](crate::types::builders::CodeAnalysisUploadContextBuilder::code_scan_name)
    pub fn build(
        self,
    ) -> ::std::result::Result<crate::types::CodeAnalysisUploadContext, ::aws_smithy_types::error::operation::BuildError>
    {
        ::std::result::Result::Ok(crate::types::CodeAnalysisUploadContext {
            code_scan_name: self.code_scan_name.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "code_scan_name",
                    "code_scan_name was not specified but it is required when building CodeAnalysisUploadContext",
                )
            })?,
        })
    }
}
