// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
impl super::Client {
    /// Constructs a fluent builder for the
    /// [`GetUsageLimits`](crate::operation::get_usage_limits::builders::GetUsageLimitsFluentBuilder)
    /// operation.
    ///
    /// - The fluent builder is configurable:
    ///   - [`profile_arn(impl Into<String>)`](crate::operation::get_usage_limits::builders::GetUsageLimitsFluentBuilder::profile_arn) / [`set_profile_arn(Option<String>)`](crate::operation::get_usage_limits::builders::GetUsageLimitsFluentBuilder::set_profile_arn):<br>required: **false**<br>The ARN of the Q Developer profile. Required for enterprise customers, optional for Builder ID users.<br>
    /// - On success, responds with
    ///   [`GetUsageLimitsOutput`](crate::operation::get_usage_limits::GetUsageLimitsOutput) with
    ///   field(s):
    ///   - [`limits(Vec::<UsageLimitList>)`](crate::operation::get_usage_limits::GetUsageLimitsOutput::limits): (undocumented)
    ///   - [`days_until_reset(i32)`](crate::operation::get_usage_limits::GetUsageLimitsOutput::days_until_reset): Number of days remaining until the usage metrics reset
    /// - On failure, responds with
    ///   [`SdkError<GetUsageLimitsError>`](crate::operation::get_usage_limits::GetUsageLimitsError)
    pub fn get_usage_limits(&self) -> crate::operation::get_usage_limits::builders::GetUsageLimitsFluentBuilder {
        crate::operation::get_usage_limits::builders::GetUsageLimitsFluentBuilder::new(self.handle.clone())
    }
}
