// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct GetTaskInput {
    #[allow(missing_docs)] // documentation missing in model
    pub task_id: ::std::option::Option<::std::string::String>,
}
impl GetTaskInput {
    #[allow(missing_docs)] // documentation missing in model
    pub fn task_id(&self) -> ::std::option::Option<&str> {
        self.task_id.as_deref()
    }
}
impl GetTaskInput {
    /// Creates a new builder-style object to manufacture
    /// [`GetTaskInput`](crate::operation::get_task::GetTaskInput).
    pub fn builder() -> crate::operation::get_task::builders::GetTaskInputBuilder {
        crate::operation::get_task::builders::GetTaskInputBuilder::default()
    }
}

/// A builder for [`GetTaskInput`](crate::operation::get_task::GetTaskInput).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct GetTaskInputBuilder {
    pub(crate) task_id: ::std::option::Option<::std::string::String>,
}
impl GetTaskInputBuilder {
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn task_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.task_id = ::std::option::Option::Some(input.into());
        self
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn set_task_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.task_id = input;
        self
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn get_task_id(&self) -> &::std::option::Option<::std::string::String> {
        &self.task_id
    }

    /// Consumes the builder and constructs a
    /// [`GetTaskInput`](crate::operation::get_task::GetTaskInput).
    pub fn build(
        self,
    ) -> ::std::result::Result<crate::operation::get_task::GetTaskInput, ::aws_smithy_types::error::operation::BuildError>
    {
        ::std::result::Result::Ok(crate::operation::get_task::GetTaskInput { task_id: self.task_id })
    }
}
