// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

/// Structure to represent create resolution response.
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct CreateResolutionOutput {
    _request_id: Option<String>,
}
impl ::aws_types::request_id::RequestId for CreateResolutionOutput {
    fn request_id(&self) -> Option<&str> {
        self._request_id.as_deref()
    }
}
impl CreateResolutionOutput {
    /// Creates a new builder-style object to manufacture
    /// [`CreateResolutionOutput`](crate::operation::create_resolution::CreateResolutionOutput).
    pub fn builder() -> crate::operation::create_resolution::builders::CreateResolutionOutputBuilder {
        crate::operation::create_resolution::builders::CreateResolutionOutputBuilder::default()
    }
}

/// A builder for
/// [`CreateResolutionOutput`](crate::operation::create_resolution::CreateResolutionOutput).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct CreateResolutionOutputBuilder {
    _request_id: Option<String>,
}
impl CreateResolutionOutputBuilder {
    pub(crate) fn _request_id(mut self, request_id: impl Into<String>) -> Self {
        self._request_id = Some(request_id.into());
        self
    }

    pub(crate) fn _set_request_id(&mut self, request_id: Option<String>) -> &mut Self {
        self._request_id = request_id;
        self
    }

    /// Consumes the builder and constructs a
    /// [`CreateResolutionOutput`](crate::operation::create_resolution::CreateResolutionOutput).
    pub fn build(self) -> crate::operation::create_resolution::CreateResolutionOutput {
        crate::operation::create_resolution::CreateResolutionOutput {
            _request_id: self._request_id,
        }
    }
}
