// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

/// Structure to represent bootstrap conversation request.
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct CreateTaskAssistConversationInput {}
impl CreateTaskAssistConversationInput {
    /// Creates a new builder-style object to manufacture
    /// [`CreateTaskAssistConversationInput`](crate::operation::create_task_assist_conversation::CreateTaskAssistConversationInput).
    pub fn builder()
    -> crate::operation::create_task_assist_conversation::builders::CreateTaskAssistConversationInputBuilder {
        crate::operation::create_task_assist_conversation::builders::CreateTaskAssistConversationInputBuilder::default()
    }
}

/// A builder for
/// [`CreateTaskAssistConversationInput`](crate::operation::create_task_assist_conversation::CreateTaskAssistConversationInput).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct CreateTaskAssistConversationInputBuilder {}
impl CreateTaskAssistConversationInputBuilder {
    /// Consumes the builder and constructs a
    /// [`CreateTaskAssistConversationInput`](crate::operation::create_task_assist_conversation::CreateTaskAssistConversationInput).
    pub fn build(
        self,
    ) -> ::std::result::Result<
        crate::operation::create_task_assist_conversation::CreateTaskAssistConversationInput,
        ::aws_smithy_types::error::operation::BuildError,
    > {
        ::std::result::Result::Ok(
            crate::operation::create_task_assist_conversation::CreateTaskAssistConversationInput {},
        )
    }
}
