// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
impl super::Client {
    /// Constructs a fluent builder for the
    /// [`SendMessage`](crate::operation::send_message::builders::SendMessageFluentBuilder)
    /// operation.
    ///
    /// - The fluent builder is configurable:
    ///   - [`origin(impl
    ///     Into<String>)`](crate::operation::send_message::builders::SendMessageFluentBuilder::origin)
    ///     / [`set_origin(Option<String>)`](crate::operation::send_message::builders::SendMessageFluentBuilder::set_origin):
    ///     <br>required: **false**<br>(undocumented)<br>
    ///   - [`source(Origin)`](crate::operation::send_message::builders::SendMessageFluentBuilder::source) / [`set_source(Option<Origin>)`](crate::operation::send_message::builders::SendMessageFluentBuilder::set_source):<br>required: **false**<br>Enum to represent the origin application conversing with Sidekick.<br>
    ///   - [`utterance(impl
    ///     Into<String>)`](crate::operation::send_message::builders::SendMessageFluentBuilder::utterance)
    ///     / [`set_utterance(Option<String>)`](crate::operation::send_message::builders::SendMessageFluentBuilder::set_utterance):
    ///     <br>required: **true**<br>(undocumented)<br>
    ///   - [`user_context(UserContext)`](crate::operation::send_message::builders::SendMessageFluentBuilder::user_context) / [`set_user_context(Option<UserContext>)`](crate::operation::send_message::builders::SendMessageFluentBuilder::set_user_context):<br>required: **false**<br>(undocumented)<br>
    ///   - [`user_settings(UserSettings)`](crate::operation::send_message::builders::SendMessageFluentBuilder::user_settings) / [`set_user_settings(Option<UserSettings>)`](crate::operation::send_message::builders::SendMessageFluentBuilder::set_user_settings):<br>required: **false**<br>(undocumented)<br>
    ///   - [`previous_utterance_id(impl Into<String>)`](crate::operation::send_message::builders::SendMessageFluentBuilder::previous_utterance_id) / [`set_previous_utterance_id(Option<String>)`](crate::operation::send_message::builders::SendMessageFluentBuilder::set_previous_utterance_id):<br>required: **false**<br>(undocumented)<br>
    ///   - [`conversation_id(impl Into<String>)`](crate::operation::send_message::builders::SendMessageFluentBuilder::conversation_id) / [`set_conversation_id(Option<String>)`](crate::operation::send_message::builders::SendMessageFluentBuilder::set_conversation_id):<br>required: **true**<br>(undocumented)<br>
    ///   - [`conversation_token(impl Into<String>)`](crate::operation::send_message::builders::SendMessageFluentBuilder::conversation_token) / [`set_conversation_token(Option<String>)`](crate::operation::send_message::builders::SendMessageFluentBuilder::set_conversation_token):<br>required: **false**<br>(undocumented)<br>
    ///   - [`dry_run(bool)`](crate::operation::send_message::builders::SendMessageFluentBuilder::dry_run) / [`set_dry_run(Option<bool>)`](crate::operation::send_message::builders::SendMessageFluentBuilder::set_dry_run):<br>required: **false**<br>(undocumented)<br>
    /// - On success, responds with
    ///   [`SendMessageOutput`](crate::operation::send_message::SendMessageOutput) with field(s):
    ///   - [`result(NellyResult)`](crate::operation::send_message::SendMessageOutput::result):
    ///     (undocumented)
    ///   - [`metadata(NellyResponseMetadata)`](crate::operation::send_message::SendMessageOutput::metadata): (undocumented)
    ///   - [`result_code(ResultCode)`](crate::operation::send_message::SendMessageOutput::result_code): (undocumented)
    /// - On failure, responds with
    ///   [`SdkError<SendMessageError>`](crate::operation::send_message::SendMessageError)
    pub fn send_message(&self) -> crate::operation::send_message::builders::SendMessageFluentBuilder {
        crate::operation::send_message::builders::SendMessageFluentBuilder::new(self.handle.clone())
    }
}
