// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct ModuleLink {
    /// For CloudWatch Troubleshooting Link Module
    pub cloud_watch_troubleshooting_link: ::std::option::Option<crate::types::CloudWatchTroubleshootingLink>,
}
impl ModuleLink {
    /// For CloudWatch Troubleshooting Link Module
    pub fn cloud_watch_troubleshooting_link(
        &self,
    ) -> ::std::option::Option<&crate::types::CloudWatchTroubleshootingLink> {
        self.cloud_watch_troubleshooting_link.as_ref()
    }
}
impl ModuleLink {
    /// Creates a new builder-style object to manufacture [`ModuleLink`](crate::types::ModuleLink).
    pub fn builder() -> crate::types::builders::ModuleLinkBuilder {
        crate::types::builders::ModuleLinkBuilder::default()
    }
}

/// A builder for [`ModuleLink`](crate::types::ModuleLink).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct ModuleLinkBuilder {
    pub(crate) cloud_watch_troubleshooting_link: ::std::option::Option<crate::types::CloudWatchTroubleshootingLink>,
}
impl ModuleLinkBuilder {
    /// For CloudWatch Troubleshooting Link Module
    pub fn cloud_watch_troubleshooting_link(mut self, input: crate::types::CloudWatchTroubleshootingLink) -> Self {
        self.cloud_watch_troubleshooting_link = ::std::option::Option::Some(input);
        self
    }

    /// For CloudWatch Troubleshooting Link Module
    pub fn set_cloud_watch_troubleshooting_link(
        mut self,
        input: ::std::option::Option<crate::types::CloudWatchTroubleshootingLink>,
    ) -> Self {
        self.cloud_watch_troubleshooting_link = input;
        self
    }

    /// For CloudWatch Troubleshooting Link Module
    pub fn get_cloud_watch_troubleshooting_link(
        &self,
    ) -> &::std::option::Option<crate::types::CloudWatchTroubleshootingLink> {
        &self.cloud_watch_troubleshooting_link
    }

    /// Consumes the builder and constructs a [`ModuleLink`](crate::types::ModuleLink).
    pub fn build(self) -> crate::types::ModuleLink {
        crate::types::ModuleLink {
            cloud_watch_troubleshooting_link: self.cloud_watch_troubleshooting_link,
        }
    }
}
