// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
impl super::Client {
    /// Constructs a fluent builder for the
    /// [`ListPluginProviders`](crate::operation::list_plugin_providers::builders::ListPluginProvidersFluentBuilder)
    /// operation. This operation supports pagination; See
    /// [`into_paginator()`](crate::operation::list_plugin_providers::builders::ListPluginProvidersFluentBuilder::into_paginator).
    ///
    ///
    /// - The fluent builder is configurable:
    ///   - [`max_results(i32)`](crate::operation::list_plugin_providers::builders::ListPluginProvidersFluentBuilder::max_results) / [`set_max_results(Option<i32>)`](crate::operation::list_plugin_providers::builders::ListPluginProvidersFluentBuilder::set_max_results):<br>required: **false**<br>(undocumented)<br>
    ///   - [`next_token(impl Into<String>)`](crate::operation::list_plugin_providers::builders::ListPluginProvidersFluentBuilder::next_token) / [`set_next_token(Option<String>)`](crate::operation::list_plugin_providers::builders::ListPluginProvidersFluentBuilder::set_next_token):<br>required: **false**<br>(undocumented)<br>
    /// - On success, responds with
    ///   [`ListPluginProvidersOutput`](crate::operation::list_plugin_providers::ListPluginProvidersOutput)
    ///   with field(s):
    ///   - [`plugin_providers(Vec::<PluginProviderMetadata>)`](crate::operation::list_plugin_providers::ListPluginProvidersOutput::plugin_providers): (undocumented)
    ///   - [`next_token(Option<String>)`](crate::operation::list_plugin_providers::ListPluginProvidersOutput::next_token): (undocumented)
    /// - On failure, responds with
    ///   [`SdkError<ListPluginProvidersError>`](crate::operation::list_plugin_providers::ListPluginProvidersError)
    pub fn list_plugin_providers(
        &self,
    ) -> crate::operation::list_plugin_providers::builders::ListPluginProvidersFluentBuilder {
        crate::operation::list_plugin_providers::builders::ListPluginProvidersFluentBuilder::new(self.handle.clone())
    }
}
