// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
impl super::Client {
    /// Constructs a fluent builder for the
    /// [`ListTasks`](crate::operation::list_tasks::builders::ListTasksFluentBuilder) operation.
    /// This operation supports pagination; See
    /// [`into_paginator()`](crate::operation::list_tasks::builders::ListTasksFluentBuilder::into_paginator).
    ///
    ///
    /// - The fluent builder is configurable:
    ///   - [`max_results(i32)`](crate::operation::list_tasks::builders::ListTasksFluentBuilder::max_results) / [`set_max_results(Option<i32>)`](crate::operation::list_tasks::builders::ListTasksFluentBuilder::set_max_results):<br>required: **false**<br>(undocumented)<br>
    ///   - [`next_token(impl
    ///     Into<String>)`](crate::operation::list_tasks::builders::ListTasksFluentBuilder::next_token)
    ///     / [`set_next_token(Option<String>)`](crate::operation::list_tasks::builders::ListTasksFluentBuilder::set_next_token):
    ///     <br>required: **false**<br>(undocumented)<br>
    ///   - [`task_filters(TaskFilter)`](crate::operation::list_tasks::builders::ListTasksFluentBuilder::task_filters) / [`set_task_filters(Option<Vec::<TaskFilter>>)`](crate::operation::list_tasks::builders::ListTasksFluentBuilder::set_task_filters):<br>required: **false**<br>(undocumented)<br>
    /// - On success, responds with
    ///   [`ListTasksOutput`](crate::operation::list_tasks::ListTasksOutput) with field(s):
    ///   - [`tasks(Vec::<TaskSummary>)`](crate::operation::list_tasks::ListTasksOutput::tasks):
    ///     (undocumented)
    ///   - [`next_token(Option<String>)`](crate::operation::list_tasks::ListTasksOutput::next_token): (undocumented)
    /// - On failure, responds with
    ///   [`SdkError<ListTasksError>`](crate::operation::list_tasks::ListTasksError)
    pub fn list_tasks(&self) -> crate::operation::list_tasks::builders::ListTasksFluentBuilder {
        crate::operation::list_tasks::builders::ListTasksFluentBuilder::new(self.handle.clone())
    }
}
